# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                # use php bin/console security:encode-password to generate hashed passwords
                users:
                    admin:
                        password: $2y$15$W0lLbAMNdg3767nGgxbHiOqNtHQoEIdARJjSomEOZQDBYgQmY9zHW #chepephec7eF
                        roles: 'ROLE_ADMIN'
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 15

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: in_memory
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login_check
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }